import os
from datetime import datetime

class MemoryPackGenerator:
    def __init__(self, result):
        self.result = result

    def build_markdown(self):
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        md = f"""# CRME MEMORY PACK

## Timestamp
{now}

---

## 🎯 Goals
"""
        for g in self.result.get("goals", []):
            md += f"- {g}\n"

        md += "\n## 🧠 Decisions\n"
        for d in self.result.get("decisions", []):
            md += f"- {d}\n"

        md += "\n## 🚀 Next Steps\n"
        for n in self.result.get("next_steps", []):
            md += f"- {n}\n"

        md += "\n---\n## System Note\nGenerated by CRME Memory Pack Generator\n"

        return md

    def save(self, md_text, base_path):
        packs_dir = os.path.join(base_path, "memory", "packs")
        os.makedirs(packs_dir, exist_ok=True)

        filename = datetime.now().strftime("memory_%Y-%m-%d_%H-%M-%S.md")
        file_path = os.path.join(packs_dir, filename)

        with open(file_path, "w", encoding="utf-8") as f:
            f.write(md_text)

        return file_path


